# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.4.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: dev@silentrhetoric.com
author_name: SilentRhetoric
contract_name: fizzbuzz
deployment_language: python
preset_name: starter
project_name: FizzBuzz

